REM***CHARGRAF
SCREEN 0, 1: WIDTH 40: KEY OFF: CLS :
ROW = 5: COL = 10
LOCATE ROW, 1
COLOR 10
PRINT TAB(COL); "        "
COLOR 4
PRINT TAB(COL); "       ‹"
COLOR 10
PRINT TAB(COL); "      ‹‹‹"
COLOR 4
PRINT TAB(COL); "     ‹‹‹‹‹"
COLOR 10
PRINT TAB(COL); "    ‹‹‹‹‹‹‹"
COLOR 4
PRINT TAB(COL); "   ‹‹‹‹‹‹‹‹‹"
COLOR 10
PRINT TAB(COL); "  ‹‹‹‹‹‹‹‹‹‹‹"
COLOR 6
PRINT TAB(COL); "       ‹"
COLOR 14
PRINT TAB(COL); "       ‹"
COLOR 6
PRINT TAB(COL); "       ‹"
END

