DECLARE SUB L1 ()
DECLARE SUB PASSWORDS ()
'                               SHARK ATTACK:
'                           WARRIORS OF THE DEEP
SCREEN 12: WIDTH 80, 60: COLOR 8
PRINT "‹ﬂﬂﬂ‹ €   € ‹ﬂﬂﬂ‹ €ﬂﬂﬂ‹ €  ‹ﬂ       ‹ﬂﬂﬂ‹ €ﬂ€ﬂ€ €ﬂ€ﬂ€ ‹ﬂﬂﬂ‹ ‹ﬂﬂﬂ‹ €  ‹ﬂ"
PRINT "ﬂ‹‹‹  €‹‹‹€ €‹‹‹€ €‹‹‹ﬂ €‹ﬂ         €‹‹‹€   €     €   €‹‹‹€ €     €‹ﬂ   ﬂ"
PRINT "‹   € €   € €   € € ﬂ‹  € ﬂ‹        €   €   €     €   €   € €   ‹ € ﬂ‹  ‹"
PRINT " ﬂﬂﬂ  ﬂ   ﬂ ﬂ   ﬂ ﬂ   ﬂ ﬂ   ﬂ       ﬂ   ﬂ   ﬂ     ﬂ   ﬂ   ﬂ  ﬂﬂﬂ  ﬂ   ﬂ"
COLOR 15
PRINT
PRINT "€   € ‹ﬂﬂﬂ‹ €ﬂﬂﬂ‹ €ﬂﬂﬂ‹ ﬂﬂ€ﬂﬂ ‹ﬂﬂﬂ‹ €ﬂﬂﬂ‹ ‹ﬂﬂﬂ‹       ‹ﬂﬂﬂ‹ €ﬂﬂﬂﬂ"
COLOR 11
PRINT "€ ‹ € €‹‹‹€ €‹‹‹ﬂ €‹‹‹ﬂ   €   €   € €‹‹‹ﬂ ﬂ‹‹‹        €   € €‹‹"
COLOR 3
PRINT "€ € € €   € € ﬂ‹  € ﬂ‹    €   €   € € ﬂ‹  ‹   €       €   € €"
COLOR 9
PRINT " ﬂﬂﬂ  ﬂ   ﬂ ﬂ   ﬂ ﬂ   ﬂ ﬂﬂﬂﬂﬂ  ﬂﬂﬂ  ﬂ   ﬂ  ﬂﬂﬂ         ﬂﬂﬂ  ﬂ"
PRINT
COLOR 1
PRINT "€ﬂ€ﬂ€ €   € €ﬂﬂﬂ        €ﬂﬂﬂ‹ €ﬂﬂﬂ  €ﬂﬂﬂ  €ﬂﬂﬂ‹"
PRINT "  €   €‹‹‹€ €‹‹         €   € €‹‹   €‹‹   €‹‹‹ﬂ"
PRINT "  €   €   € €           €   € €     €     €"
PRINT "  ﬂ   ﬂ   ﬂ ﬂﬂﬂﬂﬂ       ﬂﬂﬂﬂ  ﬂﬂﬂﬂﬂ ﬂﬂﬂﬂﬂ ﬂ"
COLOR 13
LOCATE 23, 6: PRINT "1õ           10õ    RED '?' BLOCK  BLUE '?' BLOCK  GREEN '?' BLOCK"
CIRCLE (50, 150), 25, 14, , , -.7
CIRCLE (50, 160), 25, 14, , , -.7
LINE (65, 155)-(65, 165), 14
LINE (55, 157)-(55, 167), 14
LINE (45, 157)-(45, 167), 14
LINE (35, 155)-(35, 165), 14
LINE (25, 150)-(25, 160), 14
LINE (75, 150)-(75, 160), 14
LINE (30, 155)-(30, 165), 14
LINE (40, 157)-(40, 167), 14
LINE (50, 158)-(50, 168), 14
LINE (60, 157)-(60, 167), 14
LINE (70, 155)-(70, 165), 14
CIRCLE (50, 150), 23, 14, , , -.7
CIRCLE (50, 150), 21, 15, , , -.7
CIRCLE (50, 150), 19, 14, , , -.7
CIRCLE (50, 150), 17, 15, , , -.7
CIRCLE (50, 150), 15, 14, , , -.7
CIRCLE (50, 150), 13, 15, , , -.7
CIRCLE (50, 150), 11, 14, , , -.7
CIRCLE (50, 150), 9, 15, , , -.7
CIRCLE (50, 150), 7, 14, , , -.7
CIRCLE (50, 150), 5, 15, , , -.7
CIRCLE (50, 150), 3, 14, , , -.7
CIRCLE (50, 150), 1, 15, , , -.7
'
CIRCLE (150, 150), 25, 14, , , -.7
CIRCLE (150, 160), 25, 14, , , -.7
LINE (165, 155)-(165, 165), 14
LINE (155, 157)-(155, 167), 14
LINE (145, 157)-(145, 167), 14
LINE (135, 155)-(135, 165), 14
LINE (125, 150)-(125, 160), 14
LINE (175, 150)-(175, 160), 14
LINE (130, 155)-(130, 165), 14
LINE (140, 157)-(140, 167), 14
LINE (150, 158)-(150, 168), 14
LINE (160, 157)-(160, 167), 14
LINE (170, 155)-(170, 165), 14
CIRCLE (150, 150), 23, 6, , , -.7
CIRCLE (150, 150), 21, 15, , , -.7
CIRCLE (150, 150), 19, 6, , , -.7
CIRCLE (150, 150), 17, 15, , , -.7
CIRCLE (150, 150), 15, 6, , , -.7
CIRCLE (150, 150), 13, 15, , , -.7
CIRCLE (150, 150), 11, 6, , , -.7
CIRCLE (150, 150), 9, 15, , , -.7
CIRCLE (150, 150), 7, 6, , , -.7
CIRCLE (150, 150), 5, 15, , , -.7
CIRCLE (150, 150), 3, 6, , , -.7
CIRCLE (150, 150), 1, 15, , , -.7
'
LINE (250, 120)-(300, 170), 4, B
PAINT (251, 121), 12, 4
'
LINE (350, 120)-(400, 170), 9, B
PAINT (351, 121), 11, 9
'
LINE (450, 120)-(500, 170), 2, B
PAINT (451, 121), 10, 2
'
COLOR 8
LOCATE 30, 30: PRINT "NEW GAME"
LOCATE 33, 30: PRINT "PASSWORD"
LX = 30
LY = 28
DO
LOCATE LX, LY
COLOR 7
PRINT CHR$(205); CHR$(16)
LOCATE LX, LY
PRINT "  "
SELECT CASE UCASE$(INKEY$)
 CASE "1": LX = 30
 CASE "2": LX = 33
 CASE "A": IF LX = 30 THEN L1 ELSE PASSWORDS
END SELECT
LOOP

SUB L1
CLS
C = 0
X = 50
Y = 350
SCREEN1 = 1
LIFE = 5
LSHARK$ = "C8 H5 U5 E5 F5 R10 E5 F5 R10 E5 R10 E15 R10 D5 G1 D2 G1 D2 G1 D2 G1 R15 E15 R10 F5 G15 D10 F15 G5 L10 H5 L40 NE5 F5 G5 L10 U10 L40 H5 E5 R10 U5 L16"
LSHARK2$ = "H5 U5 E5 U1 C15 U5 NR40 U1 C8 NR40 E5 R10 F5 E5 R10 F5 D1 C15 D4 G5 L10 H5 L1 G5 L9 H5"
CLSHARK$ = "C0 H5 U5 E5 F5 R10 E5 F5 R10 E5 R10 E15 R10 D5 G1 D2 G1 D2 G1 D2 G1 R15 E15 R10 F5 G15 D10 F15 G5 L10 H5 L40 NE5 F5 G5 L10 U10 L40 H5 E5 R10 U5 L16"
CLSHARK2$ = "H5 U5 E5 U1 C0 U5 NR40 U1 C0 NR40 E5 R10 F5 E5 R10 F5 D1 C0 D4 G5 L10 H5 L1 G5 L9 H5"
RSHARK$ = "C8 E5 U5 H5 G5 L10 H5 G5 L10 H5 L10 H15 L10 D5 F1 D2 F1 D2 F1 D2 F1 L15 H15 L10 G5 F15 D10 G15 F5 R10 E5 R40 NH5 G5 F5 R10 U10 R40 E5 H5 L10 U5 R16"
RSHARK2$ = "E5 U5 H5 U1 C15 U5 NL40 U1 C8 NL40 H5 L10 E5 F5 L10 G5 D1 C15 D4 F5 R10 E5 R1 F5 R9 E5"
CRSHARK$ = "C0 E5 U5 H5 G5 L10 H5 G5 L10 H5 L10 H15 L10 D5 F1 D2 F1 D2 F1 D2 F1 L15 H15 L10 G5 G15 D10 G15 F5 R10 E5 R40 NH5 G5 F5 R10 U10 R40 E5 H5 L10 U5 R16"
CRSHARK2$ = "E5 U5 H5 U1 C0 U5 NL40 U1 C0 NL40 H5 L10 E5 F5 L10 G5 D1 C0 D4 F5 R10 E5 R1 F5 R9 E5"
DO
A$ = INPUT$(1)
C = C + 1
SELECT CASE A$
 CASE "L": X = X - 1: GOSUB DRAWL
 CASE "R": X = X + 1: GOSUB DRAWR
 CASE " ":
 CASE CHR$(27): END
END SELECT
LOOP UNTIL (LIFE = 0)
END
DRAWL:
PSET (X, Y)
DRAW "X" + VARPTR$(LSHARK$)
DRAW "X" + VARPTR$(LSHARK2$)
PAINT (X + 5, Y - 15), 15
PAINT (X + 5, Y - 25), 5, 8
PAINT (X + 25, Y - 25), 5, 8
PAINT (X, Y - 5), 5, 8
LINE (X + 8, Y - 15)-(X + 9, Y - 20), 0, B
LINE (X + 28, Y - 15)-(X + 29, Y - 20), 0, B
IF C < 3 THEN
  RETURN
ELSEIF C >= 3 THEN
  PSET (X, Y), 0
  DRAW "X" + VARPTR$(CLSHARK$)
  DRAW "X" + VARPTR$(CLSHARK2$)
END IF
RETURN
DRAWR:
RETURN
END SUB

SUB PASSWORDS
END SUB

