PLAY "L8 D E F E L4 D A A G F E L8 D E F G L4 A > D C# D E. <"
PLAY "L8 D E F E L4 D A A G F E L8 D E F G L4 A > D L8 C# D E C# L4 D."
PLAY "L8 D E F E L4 D < A B- A B- A > L8 D E F E L4 D < A B- A B- A >"
PLAY "F D < B- A > F D < B- A > F D < A G F G F E"
PLAY "L8 D E F E L4 D A A G F E L8 D E F G L4 A > D C# D E. <"
PLAY "L8 D E F E L4 D A A G F E L8 D E F G L4 A > D L8 C# D E C# L4 D."

