CLS
COLOR 11
PRINT "ษออออออออออออธ",
COLOR 10
PRINT "ษออออออออออออธ",
COLOR 12
PRINT "ษออออออออออออธ"
COLOR 11
PRINT "บ WRITER 1.0 ณ",
COLOR 10
PRINT "บ WRITER 1.0 ณ",
COLOR 12
PRINT "บ WRITER 1.0 ณ"
COLOR 11
PRINT "ำฤฤฤฤฤฤฤฤฤฤฤฤู",
COLOR 10
PRINT "ำฤฤฤฤฤฤฤฤฤฤฤฤู",
COLOR 12
PRINT "ำฤฤฤฤฤฤฤฤฤฤฤฤู"
COLOR 10
PRINT "ษออออออออออออธ"
PRINT "บ WRITER 1.0 ณ"
PRINT "ำฤฤฤฤฤฤฤฤฤฤฤฤู"
COLOR 12
PRINT "ษออออออออออออธ"
PRINT "บ WRITER 1.0 ณ"
PRINT "ำฤฤฤฤฤฤฤฤฤฤฤฤู"
COLOR 13
LOCATE 8, 25: PRINT "THE NEW WAY TO WRITE YOUR LETTERS!"
A$ = INPUT$(1)
CLS
INPUT A$
LPRINT A$
END

